"""Offline provider backed by a frozen JSON snapshot.

The bundled snapshot is SYNTHETIC. Its price paths and fundamentals were
generated by tools/make_fixture.py from a seeded RNG so that the pipeline is
deterministic and testable. It is not market data and must never be read as
a view on the real companies whose tickers it borrows.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Sequence

from ..models import Bar, Fundamentals, Headline

DEFAULT_SNAPSHOT = Path(__file__).resolve().parents[2] / "data" / "snapshot.json"


class FixtureProvider:
    name = "fixture"

    def __init__(self, path: str | Path | None = None) -> None:
        self.path = Path(path) if path else DEFAULT_SNAPSHOT
        if not self.path.exists():
            raise FileNotFoundError(
                f"snapshot not found at {self.path}; run `python tools/make_fixture.py`"
            )
        with self.path.open() as fh:
            self._raw = json.load(fh)
        self.synthetic = bool(self._raw.get("synthetic", True))
        self.as_of = self._raw.get("as_of", "unknown")
        self.provenance = self._raw.get("provenance",
                                        "synthetic" if self.synthetic else "captured-live")
        self.source = self._raw.get("source", "fixture")
        self.captured_at = self._raw.get("captured_at")
        self._benchmark = self._raw.get("benchmark", "SPY")

    def is_live(self) -> bool:
        return False

    def describe(self) -> str:
        if self.synthetic:
            return f"synthetic snapshot, generated (as of {self.as_of})"
        captured = self.captured_at or self.as_of
        return f"real data captured from '{self.source}' at {captured}, replayed"

    def universe(self) -> Sequence[str]:
        return [t for t in self._raw["securities"] if t != self._benchmark]

    def fundamentals(self, ticker: str) -> Fundamentals | None:
        record = self._raw["securities"].get(ticker)
        if not record or "fundamentals" not in record:
            return None
        f = record["fundamentals"]
        return Fundamentals(
            ticker=ticker,
            name=f["name"],
            sector=f["sector"],
            price=f["price"],
            pe_trailing=f.get("pe_trailing"),
            pe_forward=f.get("pe_forward"),
            eps_trailing=f.get("eps_trailing"),
            dividend_yield=f.get("dividend_yield", 0.0),
            payout_ratio=f.get("payout_ratio"),
            market_cap=f["market_cap"],
            shares_out=f["shares_out"],
            avg_dollar_volume=f["avg_dollar_volume"],
        )

    def history(self, ticker: str) -> Sequence[Bar]:
        record = self._raw["securities"].get(ticker)
        if not record:
            return []
        return [Bar(**bar) for bar in record.get("bars", [])]

    def headlines(self, ticker: str) -> Sequence[Headline]:
        record = self._raw["securities"].get(ticker)
        if not record:
            return []
        return [
            Headline(ticker=ticker, date=h["date"], source=h["source"], title=h["title"])
            for h in record.get("headlines", [])
        ]

    def benchmark_history(self) -> Sequence[Bar]:
        return self.history(self._benchmark)
